version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: root
    command: redis-server --requirepass root
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: shortener
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: root

  log-consumer:
    build:
      context: ../LogConsumer
    container_name: log-consumer
    depends_on:
      - kafka
      - clickhouse
    env_file:
      - ../LogConsumer/.env
  
  link-redirector:
    build:
      context: ../LinkRedirector
    container_name: link-redirector
    depends_on:
      - postgres
      - redis
      - kafka
    env_file:
      - ../LinkRedirector/.env
  
  link-creator:
    build:
      context: ../LinkCreator
    container_name: link-creator
    depends_on:
      - postgres
      - redis
    env_file:
      - ../LinkCreator/.env

volumes:
  postgres_data:
  redis_data:
  kafka_data:
  clickhouse_data:
