version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shortener:
    build:
      context: ..
      dockerfile: ./build/Dockerfile
    container_name: shortener
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
       - ../.env

volumes:
  postgres_data:
